import Head from 'next/head';
import styles from '../styles/Home.module.css';
import ManualHeader from '../components/ManualHeader';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Lottery DApp</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1>Hi.</h1>
				<ManualHeader />
			</main>

			<footer className={styles.footer}></footer>
		</div>
	);
}
